#!/bin/bash
SCRIPT_NAME=$(basename $0)

set -e

# update the system
apt-get update
apt-get -y upgrade

# install git
apt-get install -y git-core

cd /root

# install AppScale
git clone git://github.com/AppScale/appscale.git
cd appscale
bash debian/appscale_build.sh

# install AppScale Tools
git clone git://github.com/AppScale/appscale-tools.git
cd appscale-tools
bash debian/appscale_build.sh
