#!/bin/bash
SCRIPT_NAME=$(basename $0)

set -e

BOOTSTRAP_URL=$1

[ -z $1 ] && echo "${SCRIPT_NAME} <bootstrap url>" 1>&2 && exit 1

BOOTSTRAP_NAME=$(basename ${BOOTSTRAP_URL})
BOOTSTRAP_PATH=/tmp/${BOOTSTRAP_NAME}

curl -L ${BOOTSTRAP_URL} -o ${BOOTSTRAP_PATH}

sudo bash ${BOOTSTRAP_PATH}
